### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by sierrodc** [electron-userland/electron-forge-templates#22] opened 2017-02-25 21:27 UTC
There is the above error using latest package of electron-forge and angular2 electron-forge-templates.

If I just execute following commands:
        `electron-forge init my-prj --template=angular2`
        `electron-forge start`

I get "Uncaught ReferenceError: exports is not defined"

A workaround is to explicitly declare exports in html:

`<script>`
    `if(!window.exports) {
      exports = module.exports;
    }`
  `</script>`

just before bootstrap.ts.

I've found this issue in electron (https://github.com/electron/electron/issues/2863) so I don't know if this issue should be addressed by template or angular-forge.

**Comment by malept** [comment] 2017-02-25 21:29
Hi, thanks for filing an issue. This is a duplicate of https://github.com/electron-userland/electron-forge-templates/issues/19#issuecomment-282398626, the link will tell you what the workaround is for this bug until a new template can be released.

**Closed as completed by malept** 2017-02-25 21:29 UTC
